"use strict";
const _imports_0$3 = "/static/logo.png";
const _imports_0$2 = "/static/icon_read.png";
const _imports_1$2 = "/static/resources/share.png";
const _imports_0$1 = "/static/icon_flag.png";
const _imports_0 = "/static/icon_about.png";
const _imports_1$1 = "/static/resources/arrow-right.png";
const _imports_1 = "/static/icon-alert.png";
exports._imports_0 = _imports_0$3;
exports._imports_0$1 = _imports_0$2;
exports._imports_0$2 = _imports_0$1;
exports._imports_0$3 = _imports_0;
exports._imports_1 = _imports_1$2;
exports._imports_1$1 = _imports_1$1;
exports._imports_1$2 = _imports_1;
